### ISSUE TITLE
svSocket and R-devel: possible bug

### ISSUE THREAD

**Issue by jcfaria** [SciViews/svSocket#6]
Hi,
I am writing to inform you that a possible bug has been detected in the svSocket (1.0.2) package in the R-devel version (4.2.0). I tested it on three machines: 1) my local Windows 10 machine; 2) virtual machine with Windows Server 2019 on AWS; 3) virtual machine with Windows 10 professional on Azure platform.

The error message is:
Error in assign("last.warning", last.warning, envir = baseenv()) : 
  cannot add binding of 'last.warning' to the base environment

About two years ago a similar error message was detected in Microsoft R Open and the problem was solved with the instruction that can be seen (see attached figure: ![svSocket_R_devel_bug](https://user-images.githubusercontent.com/878690/121598463-37da2080-ca18-11eb-864c-1db35d601db6.png)
) in line 33 of the info.R file which is open in Tinn-R . However, it is not working for R-devel.

###
 Workaround bug: MRO and svSocket
 unlockBinding("last.warning",
              baseenv())

Is it possible to know if the bug is in R or in the svSocket package? How to fix?

**Comment by phgrosjean** [comment]
Dear José Cláudio,

Thank you for the bug report. The problem is not in svSocket, but in a function in svMisc, which is a dependency. Could you install and test release v1.2.1 of svMisc to see if it solves the bug on your side, please?

***@***.***”)

Thanks.
Best,

Philippe

..............................................<°}))><........
 ) ) ) ) )
( ( ( ( (    Prof. Philippe Grosjean
 ) ) ) ) )
( ( ( ( (    Numerical Ecology
 ) ) ) ) )   Mons University, Belgium
( ( ( ( (
..............................................................

**Comment by jcfaria** [comment]
Dear Phil,
Here I tested version 1.2.1 of the svMisc package (as dependent on the main svSocket package) on R-devel (4,2,0) and MRO (4.0.2): I can say that it ran well, I didn't see any problems. Even the new svSocket version allowed removing from the info.R file of Tinn-R project the way the problem was worked around in the MRO.

#. Workaround bug: MRO and svSocket
#.unlockBinding("last.warning",
#. baseenv())

I am grateful for the attention as always.

All the best.

**Comment by phgrosjean** [comment]
Excellent! I plan more fixes and additions to {svMisc} until the end of July. So, I would not submit it to CRAN before that. In the meantime, release 1.2.1 of {svMisc} can be installed with `remotes::install_github("SciViews/svMisc@v1.2.1")`. It is identical to the current CRAN version except for this fix and two new functions to access a pCloud drive, that I think, you don't use.
